<template>
  <div class="dashboard-main-body">
<div class="card radius-12 overflow-hidden">
      <div class="card-header bg-base p-20 border-bottom"><div class="credit-wallet-toolbar"><label class="search-control"><iconify-icon icon="ri:search-line" /><input v-model="search" type="search" placeholder="Search agent, email or phone" /></label><div class="filter-actions"><button class="btn btn-outline-primary-600" :disabled="loading" @click="fetchWallets(page)"><iconify-icon icon="ri:refresh-line" class="me-6" />Refresh</button><button v-if="auth.hasPermission('credit.export')" class="btn btn-primary-600" :disabled="!wallets.length" @click="exportRows"><iconify-icon icon="ri:download-line" class="me-6" />Export</button></div></div></div>
      <LoadingState v-if="loading" message="Loading wallets..." /><div v-else-if="error" class="p-24"><ErrorState :message="error" @retry="fetchWallets(page)" /></div>
      <div v-else class="card-body p-0"><div v-if="wallets.length" class="table-responsive"><table class="table wallet-table mb-0"><thead><tr><th>Agent</th><th>Current</th><th>Purchased</th><th>Used</th><th>Remaining</th><th>Last Updated</th><th class="manage-cell">Manage</th></tr></thead><tbody><tr v-for="wallet in wallets" :key="wallet.id" class="manage-row"><td><div class="fw-semibold">{{ safeValue(wallet.agent?.name) }}</div><div class="text-secondary-light text-xs">{{ safeValue(wallet.agent?.email) }}</div></td><td class="fw-bold text-primary-600">{{ wallet.current_credits }}</td><td>{{ wallet.purchased_credits }}</td><td>{{ wallet.used_credits }}</td><td>{{ wallet.remaining_credits }}</td><td>{{ formatDate(wallet.updated_at, true) }}</td><td class="manage-cell"><button type="button" class="manage-row-button" @click="openManage(wallet)"><iconify-icon icon="lucide:settings" /> Manage</button></td></tr></tbody></table></div><EmptyState v-else icon="ri:wallet-line" title="No wallets found" message="No agent wallet matches the search." /><div v-if="wallets.length" class="px-24 pb-24"><Pagination :currentPage="page" :totalPages="totalPages" :startIndex="startIndex" :endIndex="endIndex" :totalItems="total" @page-changed="fetchWallets" /></div></div>
    </div>
    <RowManageDialog v-model="manageOpen" :title="selectedWallet?.agent?.name || `Agent #${selectedWallet?.agent_id || ''}`" :subtitle="selectedWallet ? safeValue(selectedWallet.agent?.email) : ''">
      <router-link v-if="selectedWallet" :to="`/agents/${selectedWallet.agent_id}`"><iconify-icon icon="ri:user-line" /> View agent</router-link>
      <router-link v-if="selectedWallet && auth.hasPermission('credit.history')" :to="`/credits/${selectedWallet.agent_id}/transactions`"><iconify-icon icon="ri:history-line" /> Transaction history</router-link>
      <button v-if="selectedWallet && auth.hasAnyPermission(['credit.add','credit.deduct'])" type="button" :disabled="actionId===selectedWallet.id" @click="adjust(selectedWallet)"><iconify-icon icon="ri:add-circle-line" /> Adjust credits</button>
    </RowManageDialog>
  </div>
</template>
<script setup>
import Swal from 'sweetalert2'
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import EmptyState from '@/components/common/EmptyState.vue'
import ErrorState from '@/components/common/ErrorState.vue'
import LoadingState from '@/components/common/LoadingState.vue'
import RowManageDialog from '@/components/common/RowManageDialog.vue'
import Pagination from '@/components/pagination/index.vue'
import creditService from '@/services/creditService'
import { useAuthStore } from '@/stores/auth'
import { downloadCsv, formatDate, safeValue } from '@/utils/finance'
const route=useRoute();const auth=useAuthStore();const wallets=ref([]);const search=ref(String(route.query.search||''));const loading=ref(false);const error=ref('');const actionId=ref(null);const manageOpen=ref(false);const selectedWallet=ref(null);const total=ref(0);const page=ref(1);const perPage=15;let timer
const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/perPage)));const startIndex=computed(()=>total.value?(page.value-1)*perPage:0);const endIndex=computed(()=>Math.min(startIndex.value+wallets.value.length,total.value))
function openManage(wallet){selectedWallet.value=wallet;manageOpen.value=true}
async function fetchWallets(next=1){loading.value=true;error.value='';page.value=next;try{const result=await creditService.getWallets({search:search.value,page:next,per_page:perPage});wallets.value=result?.data||result||[];total.value=result?.meta?.total??wallets.value.length}catch(err){error.value=err.message;wallets.value=[]}finally{loading.value=false}}
async function adjust(wallet){if(actionId.value)return;const actions={};if(auth.hasPermission('credit.add'))actions.add='Add credits';if(auth.hasPermission('credit.deduct'))actions.deduct='Deduct credits';const action=await Swal.fire({title:'Adjust credits',input:'select',inputOptions:actions,inputPlaceholder:'Select adjustment',showCancelButton:true});if(!action.isConfirmed)return;const current=Number(wallet.current_credits??wallet.available_credits??wallet.remaining_credits??0);const amount=await Swal.fire({title:actions[action.value],input:'number',inputAttributes:{min:1,step:1},inputLabel:'Amount',showCancelButton:true,inputValidator:(v)=>{const next=Number(v);if(!next||next<1)return'Enter a positive amount';if(action.value==='deduct'&&next>current)return`Cannot deduct more than available credits (${current}).`;return undefined}});if(!amount.isConfirmed)return;const reason=await Swal.fire({title:'Adjustment reason',input:'text',showCancelButton:true,inputValidator:(v)=>v?.trim()?undefined:'Reason is required'});if(!reason.isConfirmed)return;const remarks=await Swal.fire({title:'Adjustment remarks',input:'textarea',showCancelButton:true,inputValidator:(v)=>v?.trim()?undefined:'Remarks are required'});if(!remarks.isConfirmed)return;const confirm=await Swal.fire({title:`Confirm ${actions[action.value].toLowerCase()}?`,text:`${Number(amount.value)} credits for ${wallet.agent?.name||`Agent #${wallet.agent_id}`}`,icon:action.value==='deduct'?'warning':'question',showCancelButton:true,confirmButtonText:'Confirm',showLoaderOnConfirm:true});if(!confirm.isConfirmed)return;actionId.value=wallet.id;try{const method=action.value==='add'?creditService.addCredits:creditService.deductCredits;await method(wallet.agent_id,{amount:Number(amount.value),reason:reason.value.trim(),remarks:remarks.value.trim()});await Swal.fire({icon:'success',title:'Wallet updated',timer:1200,showConfirmButton:false});await fetchWallets(page.value)}catch(err){await Swal.fire('Adjustment failed',err.message,'error')}finally{actionId.value=null}}
function exportRows(){downloadCsv('feeta-credit-wallets.csv',[{label:'Agent',value:w=>w.agent?.name},{label:'Email',value:w=>w.agent?.email},{label:'Current',value:w=>w.current_credits},{label:'Purchased',value:w=>w.purchased_credits},{label:'Used',value:w=>w.used_credits},{label:'Updated',value:w=>w.updated_at}],wallets.value)}
watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>fetchWallets(1),450)});watch(()=>route.query.search,(value)=>{const nextSearch=String(value||'');if(nextSearch!==search.value)search.value=nextSearch});onMounted(fetchWallets);onBeforeUnmount(()=>clearTimeout(timer))
</script>
<style scoped>
.credit-wallet-toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:12px;width:100%}.filter-actions{display:flex;gap:8px;flex-wrap:wrap}.search-control{display:flex;align-items:center;gap:9px;padding:0 13px;border:1px solid #d9e0ea;border-radius:9px}.search-control input{min-height:42px;width:100%;border:0;outline:0}.wallet-table th{padding:14px 18px;color:#64748b;font-size:11px;text-transform:uppercase;background:#f8fafc;white-space:nowrap}.wallet-table td{padding:16px 18px;vertical-align:middle}.action-menu{width:36px;height:36px;display:inline-grid;place-items:center;border:1px solid #dbe3ee;border-radius:9px;background:#fff}@media(max-width:575px){.filter-actions{width:100%}.filter-actions .btn{flex:1 1 100%}}
</style>
