<template>
  <div class="dashboard-main-body">
<div class="card radius-12 overflow-hidden">
      <div class="card-header bg-base p-20 border-bottom"><div class="transfer-filters"><label class="search-control"><iconify-icon icon="ri:search-line" /><input v-model="filters.search" type="search" placeholder="Search reference, agent or sender" /></label><select v-model="filters.status" class="form-select"><option value="">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><input v-model="filters.date_from" type="date" class="form-control" /><input v-model="filters.date_to" type="date" class="form-control" /><button class="btn btn-outline-primary-600" :disabled="loading" @click="load(page)"><iconify-icon icon="ri:refresh-line" class="me-6" />Refresh</button><button v-if="auth.hasPermission('credit.export')" class="btn btn-primary-600" :disabled="!transfers.length" @click="exportRows"><iconify-icon icon="ri:download-line" class="me-6" />Export</button></div></div>
      <LoadingState v-if="loading" message="Loading manual transfers..." /><div v-else-if="error" class="p-24"><ErrorState :message="error" @retry="load(page)" /></div>
      <div v-else class="card-body p-0"><div v-if="transfers.length" class="table-responsive"><table class="table transfer-table mb-0"><thead><tr><th>Transfer</th><th>Agent</th><th>Bank / Reference</th><th>Amount</th><th>Submitted</th><th>Status</th><th class="manage-cell">Manage</th></tr></thead><tbody><tr v-for="item in transfers" :key="item.id" class="manage-row"><td>#{{ item.id }}</td><td><div class="fw-semibold">{{ safeValue(item.agent?.name) }}</div><div class="text-secondary-light text-xs">{{ safeValue(item.agent?.email) }}</div></td><td><div>{{ safeValue(item.sender_bank_name) }}</div><div class="text-secondary-light text-xs">{{ safeValue(item.transaction_reference_number) }}</div></td><td class="fw-semibold">{{ formatCurrency(item.transfer_amount) }}</td><td>{{ formatDate(item.created_at, true) }}</td><td><StatusBadge :status="item.status" /></td><td class="manage-cell"><button type="button" class="manage-row-button" @click="openManage(item)"><iconify-icon icon="lucide:settings" /> Manage</button></td></tr></tbody></table></div><EmptyState v-else icon="ri:bank-line" title="No transfers found" message="No manual transfers match the filters." /><div v-if="transfers.length" class="px-24 pb-24"><Pagination :currentPage="page" :totalPages="totalPages" :startIndex="startIndex" :endIndex="endIndex" :totalItems="total" @page-changed="load" /></div></div>
    </div>
    <RowManageDialog v-model="manageOpen" :title="selectedTransfer ? `Transfer #${selectedTransfer.id}` : ''" :subtitle="selectedTransfer ? safeValue(selectedTransfer.transaction_reference_number) : ''">
      <button v-if="selectedTransfer" type="button" :disabled="Boolean(actionId)" @click="view(selectedTransfer)"><iconify-icon icon="ri:eye-line" /> View details</button>
      <button v-if="selectedTransfer && selectedTransfer.status==='pending'&&auth.hasPermission('credit.approve')" type="button" class="text-success" :disabled="Boolean(actionId)" @click="approve(selectedTransfer)"><iconify-icon icon="ri:check-line" /> Approve</button>
      <button v-if="selectedTransfer && selectedTransfer.status==='pending'&&auth.hasPermission('credit.reject')" type="button" class="text-danger" :disabled="Boolean(actionId)" @click="reject(selectedTransfer)"><iconify-icon icon="ri:close-line" /> Reject</button>
    </RowManageDialog>
  </div>
</template>
<script setup>
import Swal from 'sweetalert2'
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import EmptyState from '@/components/common/EmptyState.vue'
import ErrorState from '@/components/common/ErrorState.vue'
import LoadingState from '@/components/common/LoadingState.vue'
import RowManageDialog from '@/components/common/RowManageDialog.vue'
import StatusBadge from '@/components/common/StatusBadge.vue'
import Pagination from '@/components/pagination/index.vue'
import creditService from '@/services/creditService'
import { useAuthStore } from '@/stores/auth'
import { downloadCsv, formatCurrency, formatDate, safeValue } from '@/utils/finance'
const route=useRoute();const auth=useAuthStore();const transfers=ref([]);const loading=ref(false);const error=ref('');const actionId=ref(null);const manageOpen=ref(false);const selectedTransfer=ref(null);const total=ref(0);const page=ref(1);const filters=reactive({search:String(route.query.search||''),status:'',date_from:'',date_to:'',per_page:15});let timer
const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/filters.per_page)));const startIndex=computed(()=>total.value?(page.value-1)*filters.per_page:0);const endIndex=computed(()=>Math.min(startIndex.value+transfers.value.length,total.value))
function openManage(item){selectedTransfer.value=item;manageOpen.value=true}
async function load(next=1){loading.value=true;error.value='';page.value=next;try{const result=await creditService.getManualTransfers({...filters,page:next});transfers.value=result?.data||result||[];total.value=result?.meta?.total??transfers.value.length}catch(err){error.value=err.message}finally{loading.value=false}}
async function view(item){await Swal.fire({title:`Transfer #${item.id}`,html:`<div class="text-start"><p><b>Agent:</b> ${safeValue(item.agent?.name)}</p><p><b>Reference:</b> ${safeValue(item.transaction_reference_number)}</p><p><b>Bank:</b> ${safeValue(item.sender_bank_name)}</p><p><b>Amount:</b> ${formatCurrency(item.transfer_amount)}</p><p><b>Credits:</b> ${safeValue(item.requested_credits)}</p><p><b>Remarks:</b> ${safeValue(item.admin_note)}</p></div>`,confirmButtonText:'Close'})}
async function approve(item){if(actionId.value)return;const remarks=await Swal.fire({title:'Approve manual transfer?',text:`${formatCurrency(item.transfer_amount)} · ${item.agent?.name||`Agent #${item.agent_id}`}`,input:'textarea',inputLabel:'Remarks',icon:'question',showCancelButton:true,confirmButtonText:'Approve',showLoaderOnConfirm:true,inputValidator:v=>v?.trim()?undefined:'Remarks are required'});if(!remarks.isConfirmed)return;actionId.value=item.id;try{await creditService.approveTransfer(item.id,{remarks:remarks.value.trim()});await Swal.fire({icon:'success',title:'Transfer approved',timer:1200,showConfirmButton:false});await load(page.value)}catch(err){await Swal.fire('Approval failed',err.message,'error')}finally{actionId.value=null}}
async function reject(item){if(actionId.value)return;const reason=await Swal.fire({title:'Reject manual transfer?',text:item.transaction_reference_number,input:'text',inputLabel:'Rejection reason',icon:'warning',showCancelButton:true,confirmButtonText:'Continue',confirmButtonColor:'#dc2626',inputValidator:v=>v?.trim()?undefined:'Reason is required'});if(!reason.isConfirmed)return;const remarks=await Swal.fire({title:'Rejection remarks',input:'textarea',showCancelButton:true,confirmButtonText:'Reject',confirmButtonColor:'#dc2626',showLoaderOnConfirm:true,inputValidator:v=>v?.trim()?undefined:'Remarks are required'});if(!remarks.isConfirmed)return;actionId.value=item.id;try{await creditService.rejectTransfer(item.id,{reason:reason.value.trim(),remarks:remarks.value.trim()});await Swal.fire({icon:'success',title:'Transfer rejected',timer:1200,showConfirmButton:false});await load(page.value)}catch(err){await Swal.fire('Rejection failed',err.message,'error')}finally{actionId.value=null}}
function exportRows(){downloadCsv('feeta-manual-transfers.csv',[{label:'ID',value:t=>t.id},{label:'Agent',value:t=>t.agent?.name},{label:'Reference',value:t=>t.transaction_reference_number},{label:'Amount',value:t=>t.transfer_amount},{label:'Credits',value:t=>t.requested_credits},{label:'Status',value:t=>t.status},{label:'Submitted',value:t=>t.created_at}],transfers.value)}
watch(()=>filters.search,()=>{clearTimeout(timer);timer=setTimeout(()=>load(1),450)});watch(()=>route.query.search,(value)=>{const nextSearch=String(value||'');if(nextSearch!==filters.search)filters.search=nextSearch});watch(()=>[filters.status,filters.date_from,filters.date_to],()=>load(1));onMounted(load);onBeforeUnmount(()=>clearTimeout(timer))
</script>
<style scoped>
.transfer-filters{display:flex;flex-wrap:wrap;align-items:center;gap:12px;width:100%}.transfer-filters>*{min-width:180px;flex:1 1 180px}.transfer-filters .search-control{min-width:260px;flex:2 1 280px}.transfer-filters button{flex:0 0 auto}.search-control{display:flex;align-items:center;gap:9px;padding:0 13px;border:1px solid #d9e0ea;border-radius:9px}.search-control input{width:100%;min-height:42px;border:0;outline:0}.transfer-table th{padding:14px 17px;color:#64748b;font-size:11px;text-transform:uppercase;background:#f8fafc;white-space:nowrap}.transfer-table td{padding:15px 17px;vertical-align:middle}.action-menu{width:36px;height:36px;display:inline-grid;place-items:center;border:1px solid #dbe3ee;border-radius:9px;background:#fff}@media(max-width:767px){.transfer-filters>*,.transfer-filters .search-control,.transfer-filters button{width:100%;flex:1 1 100%}}
</style>
